### ISSUE TITLE
Latest releases are not reflected in Webjars

### ISSUE THREAD

**Issue by anand-singh** [webjars/startbootstrap-sb-admin-2#3]
Please check the release status of below repository:
https://github.com/BlackrockDigital/startbootstrap-sb-admin-2

**Comment by anand-singh** [comment]
Hi @jamesward,

I am using this Webjar in my current in house project and facing some JS and CSS issues which are already fixed in latest release of SB Admin 2. So, Need to update it but there is no latest release found in Webjar.

Could you please look into this issue

Thanks,
Anand

**Comment by jamesward** [comment]
Do you need a new release of this WebJar?  If so, just let me know the version.

**Comment by anand-singh** [comment]
Release - [v3.3.7+1](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/releases/tag/v3.3.7%2B1)

Thanks,
Anand

**Comment by jamesward** [comment]
`3.3.7+1` was released via #4
